import type { Contact } from "./types";

const daysAgo = (n: number) => new Date(Date.now() - n * 86_400_000).toISOString();

export const seedContacts: Contact[] = [
  {
    id: "ct-nadia",
    name: "Nadia Okafor",
    email: "nadia@willowandvine.com",
    company: "Willow & Vine",
    clientId: "c-willow",
    role: "client",
    source: "attendee",
    createdAtISO: daysAgo(120),
  },
  {
    id: "ct-jonah",
    name: "Jonah Reid",
    email: "jonah.reid@harborcoffee.co",
    company: "Harbor Coffee Co.",
    clientId: "c-harbor",
    role: "client",
    source: "attendee",
    createdAtISO: daysAgo(98),
  },
  {
    id: "ct-priya-nair",
    name: "Priya Nair",
    email: "priya@harborcoffee.co",
    company: "Harbor Coffee Co.",
    clientId: "c-harbor",
    role: "client",
    source: "sent",
    createdAtISO: daysAgo(74),
  },
  {
    id: "ct-elena",
    name: "Elena Cruz",
    email: "elena.cruz@brightlinefitness.com",
    company: "Brightline Fitness",
    clientId: "c-brightline",
    role: "client",
    source: "attendee",
    createdAtISO: daysAgo(63),
  },
  {
    id: "ct-anna",
    name: "Anna Whitfield",
    email: "anna@northwindoutdoors.com",
    company: "Northwind Outdoors",
    clientId: "c-northwind",
    role: "client",
    source: "attendee",
    createdAtISO: daysAgo(51),
  },
  {
    id: "ct-rebecca",
    name: "Rebecca Voss",
    email: "rebecca@fernandfield.com",
    company: "Fern & Field",
    clientId: "c-fern",
    role: "client",
    source: "sent",
    createdAtISO: daysAgo(44),
  },
  {
    id: "ct-dev",
    name: "Dev Patel",
    email: "dev@lumen.work",
    company: "Studio",
    clientId: "c-internal",
    role: "team",
    source: "manual",
    createdAtISO: daysAgo(300),
  },
  {
    id: "ct-sara",
    name: "Sara Lin",
    email: "sara@lumen.work",
    company: "Studio",
    clientId: "c-internal",
    role: "team",
    source: "manual",
    createdAtISO: daysAgo(300),
  },
  {
    id: "ct-jordan",
    name: "Jordan Reyes",
    email: "jordan@quietcraft.studio",
    company: "Quietcraft",
    role: "freelancer",
    source: "collaborator",
    createdAtISO: daysAgo(46),
  },
  {
    id: "ct-tomas",
    name: "Tomas Ilves",
    email: "tomas.ilves@inkandgrain.com",
    company: "Ink & Grain",
    role: "freelancer",
    source: "manual",
    createdAtISO: daysAgo(28),
  },
];
