import type { ClientFile, Template } from "./types";

function ago(days: number, hour = 11) {
  const d = new Date();
  d.setDate(d.getDate() - days);
  d.setHours(hour, 0, 0, 0);
  return d.toISOString();
}

export const clientFiles: ClientFile[] = [
  {
    id: "f-har-1",
    clientId: "c-harbor",
    kind: "slides",
    name: "Harbor Coffee — Brand Deck 2026",
    source: "drive",
    url: "https://docs.google.com/presentation/d/1HarborBrandDeck2026/edit",
    tags: ["brand", "deck"],
    createdAtISO: ago(24),
    modifiedAtISO: ago(3),
  },
  {
    id: "f-har-2",
    clientId: "c-harbor",
    kind: "docs",
    name: "Harbor Coffee — Store Rollout Scope",
    source: "drive",
    url: "https://docs.google.com/document/d/1HarborRolloutScope/edit",
    tags: ["scope"],
    createdAtISO: ago(18),
    modifiedAtISO: ago(6),
  },
  {
    id: "f-har-3",
    clientId: "c-harbor",
    kind: "sheets",
    name: "Harbor Coffee — Signage Inventory",
    source: "drive",
    url: "https://docs.google.com/spreadsheets/d/1HarborSignage/edit",
    tags: ["production"],
    createdAtISO: ago(12),
    modifiedAtISO: ago(2),
  },
  {
    id: "f-har-4",
    clientId: "c-harbor",
    kind: "file",
    name: "harbor-cup-sleeve-proof.pdf",
    source: "upload",
    mime: "application/pdf",
    sizeBytes: 2_418_000,
    tags: ["print proof"],
    createdAtISO: ago(4),
  },
  {
    id: "f-bri-1",
    clientId: "c-brightline",
    kind: "sheets",
    name: "Brightline — Q3 Estimate",
    source: "drive",
    url: "https://docs.google.com/spreadsheets/d/1BrightlineQ3Estimate/edit",
    tags: ["estimate", "finance"],
    createdAtISO: ago(21),
    modifiedAtISO: ago(1),
  },
  {
    id: "f-bri-2",
    clientId: "c-brightline",
    kind: "slides",
    name: "Brightline — Campaign Sprint Readout",
    source: "drive",
    url: "https://docs.google.com/presentation/d/1BrightlineSprintReadout/edit",
    tags: ["campaign"],
    createdAtISO: ago(9),
    modifiedAtISO: ago(5),
  },
  {
    id: "f-bri-3",
    clientId: "c-brightline",
    kind: "file",
    name: "brightline-studio-shotlist.docx",
    source: "upload",
    mime: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    sizeBytes: 86_400,
    tags: ["production"],
    createdAtISO: ago(7),
  },
  {
    id: "f-wil-1",
    clientId: "c-willow",
    kind: "slides",
    name: "Willow & Vine — Moodboard Review",
    source: "drive",
    url: "https://docs.google.com/presentation/d/1WillowMoodboard/edit",
    tags: ["direction"],
    createdAtISO: ago(16),
    modifiedAtISO: ago(4),
  },
  {
    id: "f-wil-2",
    clientId: "c-willow",
    kind: "docs",
    name: "Willow & Vine — Packaging Copy Deck",
    source: "drive",
    url: "https://docs.google.com/document/d/1WillowPackagingCopy/edit",
    tags: ["copy", "packaging"],
    createdAtISO: ago(11),
    modifiedAtISO: ago(2),
  },
  {
    id: "f-wil-3",
    clientId: "c-willow",
    kind: "file",
    name: "willow-dieline-v3.pdf",
    source: "upload",
    mime: "application/pdf",
    sizeBytes: 5_120_000,
    tags: ["die-line"],
    createdAtISO: ago(3),
  },
];

export const templates: Template[] = [
  {
    id: "t-est",
    name: "Studio Estimate — standard",
    kind: "estimate",
    source: "drive",
    url: "https://docs.google.com/spreadsheets/d/1StudioEstimateTemplate/edit",
    createdAtISO: ago(120),
  },
  {
    id: "t-brand",
    name: "Brand Guidelines — master shell",
    kind: "brand",
    source: "drive",
    url: "https://docs.google.com/presentation/d/1BrandGuidelinesShell/edit",
    createdAtISO: ago(96),
  },
  {
    id: "t-har-agenda",
    clientId: "c-harbor",
    name: "Harbor Coffee — Weekly Agenda",
    kind: "agenda",
    source: "upload",
    sizeBytes: 42_000,
    createdAtISO: ago(30),
  },
  {
    id: "t-bri-prop",
    clientId: "c-brightline",
    name: "Brightline — Retainer Proposal",
    kind: "proposal",
    source: "drive",
    url: "https://docs.google.com/document/d/1BrightlineRetainerProposal/edit",
    createdAtISO: ago(45),
  },
];
