/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActionsRouteImport } from './routes/actions'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as CollaboratorsRouteImport } from './routes/collaborators'
import { Route as SearchRouteImport } from './routes/search'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as ClientsIndexRouteImport } from './routes/clients.index'
import { Route as ClientsClientIdRouteImport } from './routes/clients.$clientId'
import { Route as IdeasIndexRouteImport } from './routes/ideas.index'
import { Route as IdeasIdeaIdRouteImport } from './routes/ideas.$ideaId'
import { Route as LiveIndexRouteImport } from './routes/live.index'
import { Route as LiveSessionIdRouteImport } from './routes/live.$sessionId'
import { Route as NotesIndexRouteImport } from './routes/notes.index'
import { Route as NotesNoteIdRouteImport } from './routes/notes.$noteId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActionsRoute = ActionsRouteImport.update({
  id: '/actions',
  path: '/actions',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const CollaboratorsRoute = CollaboratorsRouteImport.update({
  id: '/collaborators',
  path: '/collaborators',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsIndexRoute = ClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsClientIdRoute = ClientsClientIdRouteImport.update({
  id: '/clients/$clientId',
  path: '/clients/$clientId',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeasIndexRoute = IdeasIndexRouteImport.update({
  id: '/ideas/',
  path: '/ideas/',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeasIdeaIdRoute = IdeasIdeaIdRouteImport.update({
  id: '/ideas/$ideaId',
  path: '/ideas/$ideaId',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveIndexRoute = LiveIndexRouteImport.update({
  id: '/live/',
  path: '/live/',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveSessionIdRoute = LiveSessionIdRouteImport.update({
  id: '/live/$sessionId',
  path: '/live/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesIndexRoute = NotesIndexRouteImport.update({
  id: '/notes/',
  path: '/notes/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesNoteIdRoute = NotesNoteIdRouteImport.update({
  id: '/notes/$noteId',
  path: '/notes/$noteId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/actions': typeof ActionsRoute
  '/alerts': typeof AlertsRoute
  '/collaborators': typeof CollaboratorsRoute
  '/search': typeof SearchRoute
  '/templates': typeof TemplatesRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/ideas/$ideaId': typeof IdeasIdeaIdRoute
  '/live/$sessionId': typeof LiveSessionIdRoute
  '/notes/$noteId': typeof NotesNoteIdRoute
  '/clients/': typeof ClientsIndexRoute
  '/ideas/': typeof IdeasIndexRoute
  '/live/': typeof LiveIndexRoute
  '/notes/': typeof NotesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/actions': typeof ActionsRoute
  '/alerts': typeof AlertsRoute
  '/collaborators': typeof CollaboratorsRoute
  '/search': typeof SearchRoute
  '/templates': typeof TemplatesRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/ideas/$ideaId': typeof IdeasIdeaIdRoute
  '/live/$sessionId': typeof LiveSessionIdRoute
  '/notes/$noteId': typeof NotesNoteIdRoute
  '/clients': typeof ClientsIndexRoute
  '/ideas': typeof IdeasIndexRoute
  '/live': typeof LiveIndexRoute
  '/notes': typeof NotesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/actions': typeof ActionsRoute
  '/alerts': typeof AlertsRoute
  '/collaborators': typeof CollaboratorsRoute
  '/search': typeof SearchRoute
  '/templates': typeof TemplatesRoute
  '/clients/$clientId': typeof ClientsClientIdRoute
  '/ideas/$ideaId': typeof IdeasIdeaIdRoute
  '/live/$sessionId': typeof LiveSessionIdRoute
  '/notes/$noteId': typeof NotesNoteIdRoute
  '/clients/': typeof ClientsIndexRoute
  '/ideas/': typeof IdeasIndexRoute
  '/live/': typeof LiveIndexRoute
  '/notes/': typeof NotesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/actions'
    | '/alerts'
    | '/collaborators'
    | '/search'
    | '/templates'
    | '/clients/$clientId'
    | '/ideas/$ideaId'
    | '/live/$sessionId'
    | '/notes/$noteId'
    | '/clients/'
    | '/ideas/'
    | '/live/'
    | '/notes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/actions'
    | '/alerts'
    | '/collaborators'
    | '/search'
    | '/templates'
    | '/clients/$clientId'
    | '/ideas/$ideaId'
    | '/live/$sessionId'
    | '/notes/$noteId'
    | '/clients'
    | '/ideas'
    | '/live'
    | '/notes'
  id:
    | '__root__'
    | '/'
    | '/actions'
    | '/alerts'
    | '/collaborators'
    | '/search'
    | '/templates'
    | '/clients/$clientId'
    | '/ideas/$ideaId'
    | '/live/$sessionId'
    | '/notes/$noteId'
    | '/clients/'
    | '/ideas/'
    | '/live/'
    | '/notes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActionsRoute: typeof ActionsRoute
  AlertsRoute: typeof AlertsRoute
  CollaboratorsRoute: typeof CollaboratorsRoute
  SearchRoute: typeof SearchRoute
  TemplatesRoute: typeof TemplatesRoute
  ClientsClientIdRoute: typeof ClientsClientIdRoute
  IdeasIdeaIdRoute: typeof IdeasIdeaIdRoute
  LiveSessionIdRoute: typeof LiveSessionIdRoute
  NotesNoteIdRoute: typeof NotesNoteIdRoute
  ClientsIndexRoute: typeof ClientsIndexRoute
  IdeasIndexRoute: typeof IdeasIndexRoute
  LiveIndexRoute: typeof LiveIndexRoute
  NotesIndexRoute: typeof NotesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actions': {
      id: '/actions'
      path: '/actions'
      fullPath: '/actions'
      preLoaderRoute: typeof ActionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collaborators': {
      id: '/collaborators'
      path: '/collaborators'
      fullPath: '/collaborators'
      preLoaderRoute: typeof CollaboratorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/': {
      id: '/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof ClientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/$clientId': {
      id: '/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof ClientsClientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ideas/': {
      id: '/ideas/'
      path: '/ideas'
      fullPath: '/ideas/'
      preLoaderRoute: typeof IdeasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ideas/$ideaId': {
      id: '/ideas/$ideaId'
      path: '/ideas/$ideaId'
      fullPath: '/ideas/$ideaId'
      preLoaderRoute: typeof IdeasIdeaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live/': {
      id: '/live/'
      path: '/live'
      fullPath: '/live/'
      preLoaderRoute: typeof LiveIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live/$sessionId': {
      id: '/live/$sessionId'
      path: '/live/$sessionId'
      fullPath: '/live/$sessionId'
      preLoaderRoute: typeof LiveSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/': {
      id: '/notes/'
      path: '/notes'
      fullPath: '/notes/'
      preLoaderRoute: typeof NotesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/$noteId': {
      id: '/notes/$noteId'
      path: '/notes/$noteId'
      fullPath: '/notes/$noteId'
      preLoaderRoute: typeof NotesNoteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActionsRoute: ActionsRoute,
  AlertsRoute: AlertsRoute,
  CollaboratorsRoute: CollaboratorsRoute,
  SearchRoute: SearchRoute,
  TemplatesRoute: TemplatesRoute,
  ClientsClientIdRoute: ClientsClientIdRoute,
  IdeasIdeaIdRoute: IdeasIdeaIdRoute,
  LiveSessionIdRoute: LiveSessionIdRoute,
  NotesNoteIdRoute: NotesNoteIdRoute,
  ClientsIndexRoute: ClientsIndexRoute,
  IdeasIndexRoute: IdeasIndexRoute,
  LiveIndexRoute: LiveIndexRoute,
  NotesIndexRoute: NotesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
